name: Daily iCal to SQLite Conversion

on:
  schedule:
    - cron: '12 2 * * *'  # Runs at 02:12 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-sqlite-database:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install icalendar requests  # Add any other dependencies your script needs

    - name: Run iCal to SQLite conversion
      run: |
        python havelland_verteiler/ical_to_sqlite.py --event-type-include "Single Day" "webcal://havelland-verteiler.de/?post_type=tribe_events&ical=1&eventDisplay=list" events.sqlite

    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add events.sqlite
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update events database" && git push)
